### ISSUE TITLE
Bilingual dictionary 

### ISSUE THREAD

**Issue by jowodo** [TheOpenDictionary/odict#550]
This project is amazing! 

Do you plan to include functionality for bilingual dictionaries? How could that be achieved? Where would it be necessary to make changes in the code? Could I misuse another feature to make two separate directed bilingual dictionaries? Do you know of any bilingual alternatives? 

Thanks for your time!

**Comment by Nickersoft** [comment]
Hey @jowodo! Super happy you like the project 😄 

This is a really interesting question, and definitely something I'd be interested in exploring! In my mind, "bilingual" can mean a couple things, but I take it based on your question it sounds like you maybe would like a bidirectional dictionary? As in, you can look up Chinese -> English and English -> Chinese words in the same file?

Because the other meaning, which is just a dictionary where the definitions are in a different language than the headwords, is actually the primary use case I've used the project for haha. So that's already doable with the current system.

Look forward to hearing more about what you'd like to achieve!

**Comment by jowodo** [comment]
Hi! 

thanks for the quick reply! I should have at least skimmed the docs and tried out a few things before writing this issue 😅
Having entry term and definition in different languages works actually pretty well for my use case as well. I was thinking about having one xml file for both directions, but now that I think about it, having two xml files makes sense. Physical bilingual dictionaries are basically also just two directional dictionaries 😂

Thanks again!
