### ISSUE TITLE
Not able to install odict shource by using command which is give in official docs

### ISSUE THREAD

**Issue by Senthil-Bala** [TheOpenDictionary/odict#736]
Not able to install odict shource by using command which is give in official docs how to fix it ?

**Comment by Nickersoft** [comment]
Ah that's super odd – yeah, I wasn't able to install any recent version using `go install` just now :/ It may be because of the default branch now being the v2 working tree. 

You can either:

1. Install via Homebrew on Mac using `brew tap TheOpenDictionary/odict && brew install odict`
2. Install the binary for your OS + architecture directly by downloading it from the [GitHub releases](https://github.com/TheOpenDictionary/odict/releases/tag/v1.23.0) and adding it to your path

Sorry for the inconvenience! This issue should go away once ODict v2 is released.
